name: Swift

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    if: "!contains(github.event.commits[0].message, '[skip ci]')"
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - uses: sersoft-gmbh/xcodebuild-action@v1
      with:
        workspace: low-key.xcworkspace
        scheme: low-key
        destination: platform=iOS Simulator,name=iPhone 11
        action: test
